---
title: "Day2 - Exercise 2"
subtitle: "Example supraclavicular - descriptive statistics"
author: "YOUR NAME"
date: "`r Sys.Date()`"
output: 
   html_document:
     toc: TRUE
     toc_float: TRUE
---

```{r setup, include = FALSE}
# settings for output
  knitr::opts_chunk$set(echo = FALSE)


# Change setting of figure width and height
  knitr::opts_chunk$set(fig.width = ggplot2::unit(10, "cm"), fig.height = ggplot2::unit(8, "cm"))

# Change options such that progress bar is not shown in the output file <- NEW!!!
  knitr::opts_knit$set(progress = FALSE, verbose = TRUE)

# libraries used in this Rmd
  library(ggplot2)
  library(tidyverse)
  library(flextable)
  library(gtsummary)
  library(knitr)
 
  
  library(cowplot)
```

```{r,  echo = FALSE, eval = TRUE}
# # Load Rdata file
#   filename <- list.files(path = "../Rdata/", pattern = "struma_prepared")
# 
#  load(file = paste0("../Rdata/", filename))
# 
# # show general information about dataset
# 
#  info$general %>% 
#    flextable::flextable() %>% 
#    flextable::font(., fontname = "Cambria (Textkörper)", part = "all") %>%
#       flextable::fontsize(., size = 10 , part = "all") %>%
#       flextable::padding(padding.top = 0,
#                          padding.bottom = 0, part = "body") %>% 
#   
#       flextable::hline(.,
#               border = officer::fp_border(color = "grey70", style = "dotted")) %>%
#       # flextable::align(., j = 1, part = "all") %>%
#       flextable::bg(., bg = "grey90", part = "header") %>% 
#       flextable::bold(., bold = TRUE, part = "header") %>% 
#       flextable::autofit()  

```


**TO DO**

* Prepare dataset 'supraclavicular'
   - Import the xlsx file and save a Rdata
      + data import & preparation in '0_supraclavicular_import_v20240305.R'
      + hint: look at 0_struma_import_v20240229.R
* Create in this Rmarkdown file the descriptive statistics